[stream]
conveyance = 0.1    # in Km^3/seg
slope = 0           # in ??
delta_t = 1         # in seconds
delta_x = 45.0      # in meters

[channel]
length = 6000       # value in meters
height = 100        # value in meters
width = 50          # value in meters
